version: "3.8"

services:
  wattamellon_app:
    build: .
    container_name: ${COMPOSE_PROJECT_NAME}
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - wattamellon_mysql
    networks:
      - app-network
    volumes:
      - .:/app

  wattamellon_mysql:
    image: mysql:8.0
    container_name: wattamellon_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${DB_PORT}:${MYSQL_DOCKER_PORT}"
    networks:
      - app-network

    volumes:
      - mysql_data:/var/lib/mysql # Persistent storage for MySQL data

networks:
  app-network:
    driver: bridge
volumes:
  mysql_data:
    driver: local
